"""
icon_map.py — the effective icon# -> item mapping = auto matches + manual fixes.

Layers (manual always wins, and survives re-running the matcher):
  data/icon_item_map.json  auto, regenerated by match_icons.py  (do NOT hand-edit)
  icon_overrides.json      manual fixes, tracked in git, override the auto match

CLI:
  python icon_map.py show 1742                 # what icon #1742 resolves to
  python icon_map.py set 1742 <item_id|name>   # pin a manual fix
  python icon_map.py unset 1742                # drop a manual fix
  python icon_map.py find "gold skull"         # search items by name -> ids
  python icon_map.py review [N]                # out/icon_review.html, worst-N first
"""
import os, json, sys

AUTO = "data/icon_item_map.json"
OVERRIDES = "icon_overrides.json"
ITEMS = "data/items.json"
CACHE = os.path.join(os.environ["LOCALAPPDATA"], "Temp", "Battlestate Games",
                     "EscapeFromTarkov", "Icon Cache", "live")


def _load(path, default):
    return json.load(open(path, encoding="utf-8")) if os.path.exists(path) else default


def items_by_id():
    return {it["id"]: it for it in _load(ITEMS, [])}


def resolve():
    """Return {icon_num: {item_id,name,short,w,h,price,source,score,margin,...}}."""
    auto = _load(AUTO, {})
    over = _load(OVERRIDES, {})
    byid = items_by_id()
    out = {}
    for num, rec in auto.items():
        r = dict(rec)
        r["source"] = "auto"
        out[num] = r
    for num, item_id in over.items():
        it = byid.get(item_id)
        if not it:
            out[num] = {"item_id": item_id, "name": "(unknown id)", "source": "override"}
            continue
        out[num] = {
            "item_id": it["id"], "name": it["name"], "short": it["shortName"],
            "w": it["width"], "h": it["height"],
            "price": it.get("avg24hPrice") or it.get("lastLowPrice") or it.get("basePrice"),
            "source": "override",
        }
    return out


def _save_overrides(over):
    json.dump(over, open(OVERRIDES, "w", encoding="utf-8"), ensure_ascii=False, indent=1)


def cmd_set(num, query):
    byid = items_by_id()
    if query in byid:
        item_id = query
    else:
        hits = [it for it in byid.values() if query.lower() in it["name"].lower()]
        if not hits:
            print("no item matches:", query); return
        if len(hits) > 1:
            print(f"{len(hits)} matches — be specific or pass an id:")
            for it in hits[:15]:
                print(f"  {it['id']}  {it['name']}")
            return
        item_id = hits[0]["id"]
    over = _load(OVERRIDES, {})
    over[num] = item_id
    _save_overrides(over)
    print(f"#{num} -> {byid[item_id]['name']}  ({item_id})  [override saved]")


def cmd_unset(num):
    over = _load(OVERRIDES, {})
    if over.pop(num, None) is not None:
        _save_overrides(over); print(f"#{num} override removed")
    else:
        print(f"#{num} had no override")


def cmd_find(query):
    for it in items_by_id().values():
        if query.lower() in it["name"].lower():
            print(f"  {it['id']}  {it['name']}  ({it['width']}x{it['height']})")


def cmd_show(num):
    print(json.dumps(resolve().get(num, {"error": "no such icon"}), indent=1, ensure_ascii=False))


def cmd_review(n=400):
    """HTML list, most-ambiguous first (low margin / high score), for manual fixing."""
    m = resolve()
    rows = []
    for num, r in m.items():
        if r.get("source") == "override":
            rank = -1e9  # show fixed ones last
        else:
            margin = r.get("margin")
            rank = (r.get("score") or 0) - (margin if margin is not None else 0)
        rows.append((rank, num, r))
    rows.sort(key=lambda x: -x[0])
    rows = rows[:n]
    cap = (CACHE.replace("\\", "/").rstrip("/") + "/")
    html = ["<meta charset=utf8><style>body{background:#222;color:#ddd;font:13px sans-serif}",
            "img{height:48px;vertical-align:middle;background:#111}",
            "tr:nth-child(even){background:#2a2a2a}td{padding:3px 8px}",
            ".o{color:#6f6}.a{color:#fc6}</style><table>",
            "<tr><th>icon</th><th>cache</th><th>-></th><th>dev</th><th>name</th>"
            "<th>score</th><th>margin</th><th>alts</th><th>src</th></tr>"]
    for _, num, r in rows:
        dev = f"data/icons/{r.get('item_id')}.webp" if r.get("item_id") else ""
        html.append(
            f"<tr><td>#{num}</td>"
            f"<td><img src='file:///{cap}{num}.png'></td><td>-&gt;</td>"
            f"<td>{'<img src=' + chr(39) + dev + chr(39) + '>' if dev else ''}</td>"
            f"<td>{r.get('name','')}</td>"
            f"<td>{r.get('score','')}</td><td>{r.get('margin','')}</td>"
            f"<td>{', '.join(r.get('alts',[]))}</td>"
            f"<td class='{ 'o' if r.get('source')=='override' else 'a'}'>{r.get('source')}</td></tr>")
    html.append("</table>")
    os.makedirs("out", exist_ok=True)
    p = os.path.join("out", "icon_review.html")
    open(p, "w", encoding="utf-8").write("\n".join(html))
    print(f"wrote {p} ({len(rows)} rows, most-ambiguous first)")
    print(f"fix with: python icon_map.py set <icon#> \"<name or id>\"")


if __name__ == "__main__":
    a = sys.argv[1:]
    if not a:
        print(__doc__); sys.exit()
    c = a[0]
    if c == "set":      cmd_set(a[1], a[2])
    elif c == "unset":  cmd_unset(a[1])
    elif c == "find":   cmd_find(a[1])
    elif c == "show":   cmd_show(a[1])
    elif c == "review": cmd_review(int(a[1]) if len(a) > 1 else 400)
    else:               print("unknown:", c)
